export const NBA = [
  { teamCH: "波士頓塞爾提克", teamEN: "BOS" },
  { teamCH: "新澤西籃網", teamEN: "NJ" },
  { teamCH: "紐約尼克", teamEN: "NY" },
  { teamCH: "費城76人", teamEN: "PHI" },
  { teamCH: "多倫多暴龍", teamEN: "TOR" },
  { teamCH: "芝加哥公牛", teamEN: "CHI" },
  { teamCH: "克里夫蘭騎士", teamEN: "CLE" },
  { teamCH: "底特律活塞", teamEN: "DET" },
  { teamCH: "印地安那溜馬", teamEN: "IND" },
  { teamCH: "密爾瓦基公鹿", teamEN: "MIL" },
  { teamCH: "亞特蘭大老鷹", teamEN: "ATL" },
  { teamCH: "紐澳良鵜鶘", teamEN: "NO" },
  { teamCH: "邁阿密熱火", teamEN: "MIA" },
  { teamCH: "奧蘭多魔術", teamEN: "ORL" },
  { teamCH: "華盛頓巫師", teamEN: "WAS" },
  { teamCH: "達拉斯獨行俠", teamEN: "DAL" },
  { teamCH: "休士頓火箭", teamEN: "HOU" },
  { teamCH: "孟斐斯灰熊", teamEN: "MEM" },
  { teamCH: "紐奧良黃蜂", teamEN: "NO" },
  { teamCH: "聖安東尼奧馬刺", teamEN: "SAS San" },
  { teamCH: "丹佛金塊", teamEN: "DEN" },
  { teamCH: "明尼蘇達灰狼", teamEN: "MIN" },
  { teamCH: "波特蘭拓荒者", teamEN: "POR" },
  { teamCH: "西雅圖超音速", teamEN: "SEA" },
  { teamCH: "猶他爵士", teamEN: "UTA" },
  { teamCH: "金州勇士", teamEN: "GSW" },
  { teamCH: "洛杉磯快艇", teamEN: "LAC" },
  { teamCH: "洛杉磯湖人", teamEN: "LAL" },
  { teamCH: "鳳凰城太陽", teamEN: "PHO" },
  { teamCH: "沙加緬度國王", teamEN: "SAC" },
];

export const MLB = [
  { teamId: 110, teamCH: "巴爾的摩金鶯隊" },
  { teamId: 111, teamCH: "波士頓紅襪隊" },
  { teamId: 147, teamCH: "紐約洋基隊" },
  { teamId: 139, teamCH: "坦帕灣光芒隊" },
  { teamId: 141, teamCH: "多倫多藍鳥隊" },
  { teamId: 116, teamCH: "底特律老虎隊" },
  { teamId: 118, teamCH: "堪薩斯市皇家隊" },
  { teamId: 114, teamCH: "克里夫蘭守護者隊" },
  { teamId: 142, teamCH: "明尼蘇達雙城隊" },
  { teamId: 145, teamCH: "芝加哥白襪隊" },
  { teamId: 108, teamCH: "洛杉磯天使隊" },
  { teamId: 117, teamCH: "休士頓太空人隊" },
  { teamId: 133, teamCH: "奧克蘭運動家隊" },
  { teamId: 136, teamCH: "西雅圖水手隊" },
  { teamId: 140, teamCH: "德州遊騎兵隊" },
  { teamId: 121, teamCH: "紐約大都會隊" },
  { teamId: 120, teamCH: "華盛頓國民隊" },
  { teamId: 143, teamCH: "費城費城人隊" },
  { teamId: 144, teamCH: "亞特蘭大勇士隊" },
  { teamId: 146, teamCH: "邁阿密馬林魚隊" },
  { teamId: 112, teamCH: "芝加哥小熊隊" },
  { teamId: 113, teamCH: "辛辛那提紅人隊" },
  { teamId: 134, teamCH: "匹茲堡海盜隊" },
  { teamId: 138, teamCH: "聖路易紅雀隊" },
  { teamId: 158, teamCH: "密爾瓦基釀酒人隊" },
  { teamId: 109, teamCH: "亞利桑那響尾蛇隊" },
  { teamId: 115, teamCH: "科羅拉多落磯隊" },
  { teamId: 119, teamCH: "洛杉磯道奇隊" },
  { teamId: 135, teamCH: "聖地牙哥教士隊" },
  { teamId: 137, teamCH: "舊金山巨人隊" },
];

export const CPBL_TEAM = [
  { name: '樂天桃猿' },
  { name: '中信兄弟' },
  { name: '富邦悍將' },
  { name: '味全龍' },
  { name: '統一7-ELEVEn獅' }
]